# Tests to run on each push to master.
name: tests
on: [push, pull_request]

jobs:
  check:
    name: Run 'cargo check'
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Check out sources
        uses: actions/checkout@v3
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Run 'cargo test'
    # GitHub VMs don't permit access to perf_event_open, so this must be disabled
    # until we have mock testing implemented.
    # See: https://github.com/jimblandy/workflow-vm-exploration
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: check out sources
        uses: actions/checkout@v3
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  docs:
    name: Run 'cargo doc'
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: check out sources
        uses: actions/checkout@v3
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items

  fmt:
    name: Run 'cargo fmt --check'
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: check out sources
        uses: actions/checkout@v3
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  clippy:
    name: Run 'cargo clippy'
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: check out sources
        uses: actions/checkout@v3
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
